baseURL = "http://example.org/"
languageCode = "en-us"
title = "Aiswarya Prakasan"
theme = "ananke"

[params]
  favicon = ""
  site_logo = ""
  description = "Software Developer, writer."
  facebook = ""
  twitter = "https://twitter.com/ashprakasan"
  instagram = ""
  youtube = ""
  github = ""
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  commento = true
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  #featured_image = "/images/gohugo-default-sample-hero-image.jpg"
  recent_posts_number = 2
